### PR TITLE
Upgrade aws sdk and support for fargate

### PR DESCRIPTION
**Pull request by renanrt**
In order to support Fargate:

- [x] Upgrade aws sdk to 1.14.17
- [x] Pass on parameters related to FARGATE (cpu, memory, requires compatibilities and execute role arn)

### CODE REVIEW

**Review by gustavosoares — APPROVED** [review]
looking good. I've added @NZKoz  and @nzwalker as reviewers as well. My only concern is if `ExecutionRoleArn` will only take effect if it is not `nil`, which would be ideal.. this way we woudn't have to update all ci users. 😳

**Comment by NZKoz** [comment]
Do you want to update to dep at the same time?  it will remove a lot of code from vendor?

**Comment by renanrt** [comment]
sure.

**Comment by renanrt** [comment]
image

**Pull request merged**
